name: Mocha CI

on:
  push:
    branches:
      - master
    paths:
    - "test/**"
    - ".github/workflows/ci.yml"

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Test
      run: ([ -z $CG_USERNAME ] || [ -z $CG_PASSWORD ] || npm test)
      env:
        CG_USERNAME: ${{ secrets.CG_USERNAME }}
        CG_PASSWORD: ${{ secrets.CG_PASSWORD }}
