name: Daily

on:
  schedule:
    - cron: '0 2,6,9,12,16,20 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Test
      run: ([ -z $CG_USERNAME ] || [ -z $CG_PASSWORD ] || npm test)
      env:
        CG_USERNAME: ${{ secrets.CG_USERNAME }}
        CG_PASSWORD: ${{ secrets.CG_PASSWORD }}

  ##################################
  ### Run when a schedule failed ###
  ##################################
  restart_when_failed:
    name: Restarts the scheduled run when it failed
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && failure()
    needs: [build]
    steps:
      - name: Retry the workflow
        run: |
          curl -i \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.ACTIONS_PAT }}" \
          https://api.github.com/repos/FinbertMDS/webdriver_ci/actions/workflows/23303722/dispatches \
          -d '{"ref": "${{ github.ref }}" }'
