name: Daily Apps

on:
  schedule:
    - cron: '0 1,6 * * *'
  workflow_dispatch:

jobs:
  build:
    # if: (github.event_name == 'schedule')
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'apps'
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
    - name: Install Appium
      uses: FinbertMDS/setup-appium@latest
      with:
        appium-version: "1.20.2"
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Run Appium Tests
      uses: reactivecircus/android-emulator-runner@v2
      env:
        CG_USERNAME: ${{ secrets.CG_USERNAME }}
        CG_PASSWORD: ${{ secrets.CG_PASSWORD }}
      with:
        api-level: 28
        target: google_apis
        emulator-build: 7425822
        script: "[-z $CG_USERNAME ] || [ -z $CG_PASSWORD ] || (sleep 60 && yarn test)"
    - name: upload-artifact
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: upload-screenshots
        path: screenshots
    - name: remove-screenshots
      if: ${{ failure() }}
      run: rm -rf ./screenshots

  ##################################
  ### Run when a schedule failed ###
  ##################################
  restart_when_failed:
    name: Restarts the scheduled run when it failed
    runs-on: macos-latest
    if: github.event_name == 'schedule' && failure()
    needs: [build]
    steps:
      - name: Retry the workflow
        run: |
          curl -i \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.ACTIONS_PAT }}" \
          https://api.github.com/repos/FinbertMDS/webdriver_ci/actions/workflows/42844073/dispatches \
          -d '{"ref": "${{ github.ref }}" }'