name: Build and Distribute on Push to Master

on:
  push:
    branches:
      - master

jobs:
  build-ios:
    name: Build and Upload iOS to TestFlight
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key for GitHub
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MATCH_SSH_KEY }}

      - name: Clone mobile_certs 1
        run: |
          git clone git@github.com:FinbertMDS/mobile_certs.git
      
